name: ci
on: [push]
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@testing
        with:
          go-version: '*'
      - run: script/generate --check
      - run: script/test
      - run: script/lint
      - name: sayhi
        run: |
          set -ex
          got="$(script/sayhi)"
          if [ "$got" != "hi" ]; then
            echo "::error ::wrong output expected 'hi' but got '$got'"
            exit 1
          fi
