name: ci
on:
  push:
  workflow_dispatch:
jobs:
  cibuild:
    name: cibuild
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-2022
          - macos-11
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
#      - uses: WillAbides/setup-go-faster@v1.10.0
#        with:
#          go-version: 1.19
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - run: script/lint
      - run: script/generate --check
      - run: script/test
      - name: sayhi
        run: |
          set -ex
          go version
          got="$(script/sayhi)"
          if [ "$got" != "hi" ]; then
            echo "::error ::wrong output expected 'hi' but got '$got'"
            exit 1
          fi
#  test-tip:
#    name: test-tip
#    strategy:
#      fail-fast: false
#      matrix:
#        os:
#          - ubuntu-22.04
#          - ubuntu-20.04
#          - windows-2022
#          - macos-11
#    runs-on: ${{ matrix.os }}
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - uses: actions/checkout@v3
#      - uses: WillAbides/setup-go-faster@v1.9.0
#        with:
#          go-version: tip
#      - run: go version
#      - name: sayhi
#        run: |
#          set -ex
#          got="$(script/sayhi)"
#          if [ "$got" != "hi" ]; then
#            echo "::error ::wrong output expected 'hi' but got '$got'"
#            exit 1
#          fi
