name: ci
on: [push]
jobs:
  cibuild:
    name: cibuild
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.6.0
        with:
          go-version: '*'
      - run: script/generate --check
      - run: script/test
      - run: script/lint
      - name: sayhi
        run: |
          set -ex
          got="$(script/sayhi)"
          if [ "$got" != "hi" ]; then
            echo "::error ::wrong output expected 'hi' but got '$got'"
            exit 1
          fi
  test-tip:
    name: test-tip
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - windows-2019
          - macos-10.15
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.6.0
        with:
          go-version: tip
      - run: go version
      - name: sayhi
        run: |
          set -ex
          got="$(script/sayhi)"
          if [ "$got" != "hi" ]; then
            echo "::error ::wrong output expected 'hi' but got '$got'"
            exit 1
          fi
