name: multi-test
on:
  push:
  workflow_dispatch:
jobs:
  toolchain-test:
    runs-on: ubuntu-22.04
    steps:
      - run: go version
      - uses: WillAbides/setup-go-faster@v1.9.1
        with:
          go-version: 1.21rc4
      - run: go version
      - run:
          GOTOOLCHAIN=go1.21.1 go version
