name: multi-test
on:
  push:
  workflow_dispatch:
jobs:
  toolchain-test:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -haltr "$RUNNER_TOOL_CACHE/go"
      - run: which -a go
      - run: go version
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.12.0
        with:
          go-version-file: go.mod
      - run: go version
      - run:
          go version
