name: multi-test
on:
  push:
  workflow_dispatch:
jobs:
  multi-test:
    name: multi-test
    strategy:
      fail-fast: false
      matrix:
        action:
          - setup-go-faster
          - setup-go
        os:
          - ubuntu-22.04
          - windows-2022
        go-version-spec:
          - '1.21.x'
          - '1.20.x'
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - if: matrix.action == 'setup-go-faster'
        id: setup_go_faster
        uses: WillAbides/setup-go-faster@matcher
        with:
          go-version: ${{ matrix.go-version-spec }}
      - if: matrix.action == 'setup-go-faster'
        name: outputs
        run: |
          echo '*********** go version ***********'
          go version
          echo '*********** outputs ***********'
          echo '${{ toJson( steps.setup_go_faster.outputs ) }}' | jq .
          echo '*********** env ************'
          env
          echo '*********** go env ***********'
          go env
      - if: matrix.action == 'setup-go'
        id: setup_go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version-spec }}
          cache: false
      - if: matrix.action == 'setup-go'
        name: outputs
        run: |
          echo '*********** go version ***********'
          go version
          echo '*********** outputs ***********'
          echo '${{ toJson( steps.setup_go.outputs ) }}' | jq .
          echo '*********** env ************'
          env
          echo '*********** go env ***********'
          go env
