name: multi-test
on:
  push:
  workflow_dispatch:
jobs:
  multi-test:
    name: multi-test
    strategy:
      fail-fast: false
      matrix:
        action:
          - setup-go-faster
          - setup-go
        go-version-spec:
          - '1.21'
          - '1.21.x'
          - '1.21.0'
          - '1.20'
          - '1.20.x'
          - '1.20.0'
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - if: matrix.action == 'setup-go-faster'
        uses: WillAbides/setup-go-faster@v1.10.0
        with:
          go-version: ${{ matrix.go-version-spec }}
      - if: matrix.action == 'setup-go'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version-spec }}
          cache: false
