name: speedrun
on:
  workflow_dispatch:
env:
  GO_VERSION: 1.21.0
jobs:
  setup-go-faster:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: WillAbides/setup-go-faster@main
        with:
          go-version: ${{ env.GO_VERSION }}
  setup-go-v4:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
