name: speedrun
on:
  push:
  workflow_dispatch:
jobs:
  setup-go-faster:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: 1.19.x
  setup-go:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
